"""Spike: inspect edgar_corpus/ to make chunking a dataset-driven decision.

Deterministic analysis (no LLM, no writes to data/). Reports file/size
distribution, header-field coverage, the XBRL-blob vs prose split, section-
heading patterns per form, and text-structure stats (blank-line paragraphs vs
line lengths) — then records the chosen chunk_size / chunk_overlap (in
characters, for RecursiveCharacterTextSplitter) with rationale.

Run:  python scripts/inspect_corpus.py
Output: prints a summary and writes architecture/corpus_notes.md (idempotent —
no timestamps, so re-running yields an identical file).
"""

from __future__ import annotations

import json
import re
import statistics
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from src.config import settings  # noqa: E402

SEP = re.compile(r"={10,}")
PROSE = re.compile(r"UNITED STATES\s*SECURITIES AND EXCHANGE COMMISSION|FORM 10-[KQ]", re.I)
ITEM = re.compile(r"^\s*Item\s+(\d+)([A-Za-z]?)\b", re.I | re.M)
HEADER_FIELDS = [
    "Company", "Ticker", "Filing Type", "Filing Date",
    "Report Period", "Quarter", "CIK", "Source", "URL",
]

# --- Chunking decision (characters). Justified by the findings below. ---
CHUNK_SIZE = 3000       # ~750 tokens: enough context to answer, precise enough to rank
CHUNK_OVERLAP = 300     # 10% — preserves context across chunk boundaries


# --- pure helpers (unit-tested) ---------------------------------------------
def split_header_body(raw: str) -> tuple[str, str]:
    parts = SEP.split(raw, maxsplit=1)
    return (parts[0], parts[1]) if len(parts) == 2 else (raw, "")


def header_fields_present(header: str) -> dict[str, bool]:
    return {f: bool(re.search(rf"^{re.escape(f)}\s*:", header, re.M)) for f in HEADER_FIELDS}


def find_prose_start(body: str) -> int:
    m = PROSE.search(body)
    return m.start() if m else -1


def detect_items(text: str) -> list[str]:
    """Unique 'Item N[A]' labels in first-seen order."""
    seen: dict[str, int] = {}
    for m in ITEM.finditer(text):
        label = f"Item {int(m.group(1))}{m.group(2).upper()}"
        seen.setdefault(label, m.start())
    return sorted(seen, key=lambda k: seen[k])


# --- aggregation ------------------------------------------------------------
def pctile(xs: list[int], p: float) -> int:
    if not xs:
        return 0
    s = sorted(xs)
    k = (len(s) - 1) * p / 100
    lo = int(k)
    hi = min(lo + 1, len(s) - 1)
    return int(s[lo] + (s[hi] - s[lo]) * (k - lo))


def analyze(raw: str) -> dict:
    header, body = split_header_body(raw)
    prose_start = find_prose_start(body)
    prose = body[prose_start:] if prose_start >= 0 else body
    blank_paras = [p for p in re.split(r"\n\s*\n", prose) if p.strip()]
    lines = [len(ln) for ln in prose.split("\n") if ln.strip()]
    return {
        "total_chars": len(raw),
        "xbrl_chars": max(prose_start, 0),
        "prose_chars": len(prose),
        "prose_found": prose_start >= 0,
        "fields": header_fields_present(header),
        "items": set(detect_items(prose)),
        "n_blank_paras": len(blank_paras),
        "lines": lines,
    }


def main() -> None:
    manifest = json.loads((settings.corpus_path / "manifest.json").read_text("utf-8"))
    files = manifest["files"]

    rows, all_lines, blank_para_counts = [], [], []
    forms: Counter[str] = Counter()
    items_by_form: dict[str, Counter[str]] = {"10-K": Counter(), "10-Q": Counter()}
    field_hits: Counter[str] = Counter()

    for fname in files:
        form = "10-K" if "_10K_" in fname else "10-Q" if "_10Q_" in fname else "?"
        forms[form] += 1
        a = analyze((settings.corpus_path / fname).read_text("utf-8", errors="replace"))
        rows.append(a)
        all_lines.extend(a["lines"])
        blank_para_counts.append(a["n_blank_paras"])
        for f, present in a["fields"].items():
            field_hits[f] += int(present)
        if form in items_by_form:
            for it in a["items"]:
                items_by_form[form][it] += 1

    n = len(rows)
    sizes = [r["total_chars"] for r in rows]
    xbrl = [r["xbrl_chars"] for r in rows]
    prose = [r["prose_chars"] for r in rows]
    prose_found = sum(r["prose_found"] for r in rows)
    blank_med = int(statistics.median(blank_para_counts)) if blank_para_counts else 0

    def kb(x: int) -> str:
        return f"{x / 1000:,.0f} KB"

    lines = [
        "# Corpus Notes (auto-generated by scripts/inspect_corpus.py)",
        "",
        "Deterministic inspection of `edgar_corpus/` to ground chunking decisions in the data.",
        "Re-generate with `python scripts/inspect_corpus.py` (idempotent — no timestamps).",
        "",
        "## Files",
        f"- Total: **{n}** filings ({', '.join(f'{k}: {v}' for k, v in sorted(forms.items()))}).",
        f"- Size (chars): p50 {kb(pctile(sizes,50))}, p90 {kb(pctile(sizes,90))}, "
        f"max {kb(max(sizes))}, min {kb(min(sizes))}.",
        "",
        "## XBRL blob vs prose (per file)",
        f"- Prose anchor found in **{prose_found}/{n}** files "
        f"(`UNITED STATES … SEC` / `FORM 10-K/Q`).",
        f"- Leading XBRL blob (chars): p50 {kb(pctile(xbrl,50))}, p90 {kb(pctile(xbrl,90))}, "
        f"max {kb(max(xbrl))} — this is what Stage 2 (cleaning) must strip.",
        f"- Prose body after the blob (chars): p50 {kb(pctile(prose,50))}, "
        f"p90 {kb(pctile(prose,90))}, max {kb(max(prose))}.",
        "",
        "## Header field coverage",
    ]
    for f in HEADER_FIELDS:
        lines.append(f"- `{f}`: {field_hits[f]}/{n} ({100*field_hits[f]//n}%)")
    lines += [
        "",
        "> Implication: metadata extraction (Stage 3) must tolerate missing fields "
        "(e.g. `Report Period` / `Quarter`) and backfill from the filename.",
        "",
        "## Section headings per form (files containing each item)",
    ]
    for form in ("10-K", "10-Q"):
        top = items_by_form[form].most_common(12)
        lines.append(f"- **{form}**: " + ", ".join(f"{it} ({c})" for it, c in top))
    lines += [
        "",
        "## Text structure (the key chunking finding)",
        f"- Blank-line paragraphs are **scarce**: median **{blank_med}** blank-line-delimited "
        f"segments per filing — the prose is essentially one long newline-run, not paragraph text.",
        f"- Line lengths (chars): p50 {pctile(all_lines,50)}, p90 {pctile(all_lines,90)}, "
        f"p99 {pctile(all_lines,99)} over {len(all_lines):,} non-blank lines "
        f"(long lines are tables/aligned rows).",
        "",
        "## Decision — chunking (characters; RecursiveCharacterTextSplitter)",
        f"- **chunk_size = {CHUNK_SIZE}**, **chunk_overlap = {CHUNK_OVERLAP}** (~10%).",
        "- Rationale: because blank-line paragraph structure is essentially absent, we cannot "
        "chunk on paragraphs. Instead use a fixed character window (~750 tokens at ~4 chars/token) "
        f"with the recursive separator hierarchy `['\\n\\n', '\\n', '. ', ' ', '']`, splitting "
        "**within** detected sections (Stage 4) and never across them. "
        f"{CHUNK_SIZE} chars is large enough to carry a table plus its surrounding narrative, "
        f"small enough to rank precisely; {CHUNK_OVERLAP}-char overlap preserves cross-boundary "
        "context. These are a starting point — validated/tuned later by the retrieval eval.",
        "",
    ]
    (ROOT / "architecture" / "corpus_notes.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Analyzed {n} filings. Prose anchor found in {prose_found}/{n}.")
    print(f"Blank-line paragraphs per filing (median): {blank_med}  -> paragraph chunking is not viable.")
    print(f"Line length p50/p90: {pctile(all_lines,50)}/{pctile(all_lines,90)} chars.")
    print(f"DECISION  chunk_size={CHUNK_SIZE}  chunk_overlap={CHUNK_OVERLAP}")
    print("Wrote architecture/corpus_notes.md")


if __name__ == "__main__":
    main()
